// FOLLOWERS CONSTANTS
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL'
export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
// UNFOLLOW CONSTANTS
export const UNFOLLOW_USER_FAIL = 'UNFOLLOW_USER_FAIL'
export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST'
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS'
// GET FOLLOWERS CONSTANTS
export const GET_FOLLOWER_LIST_FAIL = 'GET_FOLLOWER_LIST_FAIL'
export const GET_FOLLOWER_LIST_REQUEST = 'GET_FOLLOWER_LIST_REQUEST'
export const GET_FOLLOWER_LIST_SUCCESS = 'GET_FOLLOWER_LIST_SUCCESS'