// FOLLOWERS CONSTANTS
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL'
export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
// UNFOLLOW CONSTANTS
export const UNFOLLOW_USER_FAIL = 'UNFOLLOW_USER_FAIL'
export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST'
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS'
// GET FOLLOWERS CONSTANTS
export const GET_FOLLOWERS_INFO_FAIL = 'GET_FOLLOWERS_INFO_FAIL'
export const GET_FOLLOWERS_INFO_REQUEST = 'GET_FOLLOWERS_INFO_REQUEST'
export const GET_FOLLOWERS_INFO_SUCCESS = 'GET_FOLLOWERS_INFO_SUCCESS'