// CREATE POST CONSTANTS
export const CREATE_POST_COMMENT_FAIL = 'CREATE_POST_COMMENT_FAIL'
export const CREATE_POST_COMMENT_REQUEST = 'CREATE_POST_COMMENT_REQUEST'
export const CREATE_POST_COMMENT_SUCCESS = 'CREATE_POST_COMMENT_SUCCESS'
// DELETE POST CONSTANTS
export const DELETE_POST_COMMENT_FAIL = 'DELETE_POST_COMMENT_FAIL'
export const DELETE_POST_COMMENT_REQUEST = 'DELETE_POST_COMMENT_REQUEST'
export const DELETE_POST_COMMENT_SUCCESS = 'DELETE_POST_COMMENT_SUCCESS'