// POST POST CONSTANTS
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
// GET POSTS CONSTANTS
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL'
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
// DELETE POSTS CONSTANTS
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
// LIKE POSTS CONSTANTS
export const LIKE_POST = 'DELETE_POST_FAIL'
export const LIKE_POST_FAIL = 'DELETE_POST_SUCCESS'
export const UNLIKE_POST = 'DELETE_POST_REQUEST'
export const UNLIKE_POST_FAIL = 'DELETE_POST_SUCCESS'