// CHANGE PROFILE PICTURE CONSTANTS
export const UPDATE_PROFILE_PICTURE_FAIL = 'UPDATE_PROFILE_PICTURE_FAIL'
export const UPDATE_PROFILE_PICTURE_REQUEST = 'UPDATE_PROFILE_PICTURE_REQUEST'
export const UPDATE_PROFILE_PICTURE_SUCCESS = 'UPDATE_PROFILE_PICTURE_SUCCESS'