// GET USER INFO CONSTANTS
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL'
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
// GET ALL USERS CONSTANTS
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL'
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
